on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build Nix targets
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Nix Flake Checker
        uses: DeterminateSystems/flake-checker-action@v8
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13
      - name: Build default package
        run: nix build .#jibriel
